name: MYSQL_DATABASE_TEST_ENV

services:

  #MYSQL
  db:
    container_name: test_database_mysql
    image: mysql:latest
    volumes:
      - database:/var/lib/mysql
    restart: always
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "db" ]
      timeout: 1s
      retries: 10

  #PHPMYADMIN
  phpmyadmin:
    container_name: test_database_phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    image: phpmyadmin
    restart: always
    ports:
      - '${PHP_MY_ADMIN_PORT}:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: 2000M

volumes:
  database:
    name: test_database_volume
